language: node_js
node_js:
  - lts/*
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add /tmp/deploy_rsa
  - chmod +x ./ci/deploy-production
  - chmod +x ./ci/deploy-recette
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./ci/deploy-production; fi
  - if [ "$TRAVIS_BRANCH" = "recette-2021" ]; then ./ci/deploy-recette; fi
  - pwd
  # - cd "$PROJET_RECETTE"/frontend && npm install
  # - pm2 restart recette-frontend
