language: node_js
node_js:
  - node
before_install:
  - openssl aes-256-cbc -K $encrypted_ed4a56cebe50_key -iv $encrypted_ed4a56cebe50_iv
    -in deploy_rsa.enc -out ~\/.ssh/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~\/.ssh/deploy_rsa
  - echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ~\/.ssh/deploy_rsa
  - chmod +x ./ci/deploy-production
  - chmod +x ./ci/deploy-recette
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./ci/deploy-production; fi
  - if [ "$TRAVIS_BRANCH" = "recette" ]; then ./ci/deploy-recette; fi
