#!/bin/sh
rsync -az -O --force --delete --progress --exclude-from=".rsyncignore" -e "ssh -p $PORT" ./ "$USERNAME"@"$HOST":"$PROJECT"
ssh -p $PORT $USERNAME@$HOST "
	cd $PROJECT && yarn install && npm run build;
	cd $PROJECT/backend && yarn install && NODE_ENV=production npm run build;
	pm2 restart frontend
	pm2 restart backend
	exit;
"
