index:
  path: /
  controller: App\Controller\HomeController::index
blog:
  path: /blog
  controller: App\Controller\BlogController::index
post:
  path: /post/{slug}
  controller: App\Controller\PostController::index
  defaults:
    id: slug
