#!/bin/sh
rsync -az -O --force --delete --progress --exclude-from=".rsyncignore" -e "ssh -p $PORT" ./ "$USERNAME"@"$HOST":"$PROJET_PROD"
ssh -p $PORT $USERNAME@$HOST "
	cd $PROJET_PROD/backend && npm install;
	pm2 restart backend
	cd $PROJET_PROD/frontend && npm install && NODE_ENV=production npm run build;
	pm2 restart frontend
	exit;
"
