#!/bin/sh
rsync -az -O --force --delete --progress --exclude-from=".rsyncignore" -e "ssh -p $PORT" ./ "$USERNAME"@"$HOST":"$PROJET_RECETTE"
ssh -p $PORT $USERNAME@$HOST "
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
	source ~/.bashrc
	nvm use --lts

	cd $PROJET_RECETTE/frontend && npm install;
	pm2 restart recette-frontend
	exit;
"
