#!/bin/sh
rsync -az -O --force --delete --progress --exclude-from=".rsyncignore" -e "ssh -p $PORT" ./ "$USERNAME"@"$HOST":"$PROJET_RECETTE"
ssh -p $PORT $USERNAME@$HOST "
	cd $PROJET_RECETTE && npm install && npm run build;
	cd $PROJET_RECETTE/backend && npm install && NODE_ENV=production npm run build;
	pm2 restart recette-frontend
	pm2 restart recette-backend
	exit;
"
